### PR TITLE
Add id to json content types

### PR DESCRIPTION
**Pull request by cepages**
Tests will probably fail!

### CODE REVIEW

**Comment by cepages** [comment]
@KevinEtienne @Ian-Foote @adam-incuna please review (written by @meshy)

**Comment by meshy** [comment]
@Ian-Foote do you have time to tag and push a release of this?

**Comment by Ian-Foote** [comment]
Done.

**Comment by cepages** [comment]
@Ian-Foote with done, do you mean deployed?

 I'm not asking to deploy it, just if that's the meaning..... you know what I mean :)

**Comment by Ian-Foote** [comment]
It means the latest version of the library can be installed.

**Comment by meshy** [comment]
Thanks, @Ian-Foote

**Pull request merged**
